name: Test and Coverage with Codecov

on:
  pull_request:
    branches: [main, develop]  # Se activa para PRs contra main o develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 24
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '24'

      - name: Grant execute permission to Gradle
        run: chmod +x ./gradlew

      - name: Run tests and generate JaCoCo report
        run: ./gradlew test jacocoTestReport

      - name: Upload JaCoCo report to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: build/reports/jacoco/test/jacocoTestReport.xml
          flags: unittests
          name: codecov-coverage
          fail_ci_if_error: true
